

definitions:
  images:
    - image: &dibkphp
        name: dibknoe.azurecr.io/php:latest
        username: $REGISTRY_USERNAME
        password: $REGISTRY_PASSWORD

# Setter maksimum kjøretid for et steg
options:
  max-time: 60

image: *dibkphp

pipelines:
  custom:
    jamf2pureservice:
      - step:
          name: Synkroniser mellom Jamf Pro og Pureservice
          deployment: production
          script:
            - cp .env.example .env
            - composer install --no-dev
            - ./artisan jamf2pureservice:run
    svarinn2pureservice:
      - step:
          name: Henter privatnøkkel for SvarInn fra Azure Key Vault
          image: mcr.microsoft.com/azure-cli
          clone:
            enabled: false
          artifacts:
            - "*.pem"
            - "*.xlsx"
            - "*.json"
          script:
            - LOGIN=$(az login --service-principal -u ${AZURE_SP_ID} -p=${AZURE_SP_SECRET} --tenant ${AZURE_SP_TENANT})
            - az keyvault secret download --file privatekey.tmp --name ${AZURE_KV_KEY_NAME} --vault-name ${AZURE_KV_NAME}
            - echo -e "-----BEGIN PRIVATE KEY-----\n$(cat privatekey.tmp)\n-----END PRIVATE KEY-----" > privatekey.pem
            - echo "Laster ned kommunefil fra Azure Blob Storage"
            - az storage blob download --auth-mode login --file ${BITBUCKET_CLONE_DIR}/${SVARINN_EXCEL_LOOKUP_FILE} --name ${SVARINN_EXCEL_LOOKUP_FILE} --container-name ${STORAGE_CONTAINER} --no-progress --account-name ${STORAGE_ACCOUNT_NAME}
            - az storage blob download --auth-mode login --file ${BITBUCKET_CLONE_DIR}/example.json --name example.json --container-name ${STORAGE_CONTAINER} --no-progress --account-name ${STORAGE_ACCOUNT_NAME}
            - az logout
            - ls -lh

      - step:
          name: Ser etter innkommende forsendelser i SvarInn
          script:
            - echo 'Installerer OpenJDK 11 og CMS dekrypter'
            - apk add openjdk11 unzip
            - curl -LO https://github.com/DirektoratetForByggkvalitet/svarut-dekrypter/releases/download/${DEKRYPTER_VER}/dekrypter-${DEKRYPTER_VER}-dist.zip
            - unzip dekrypter-${DEKRYPTER_VER}-dist.zip && rm dekrypter-${DEKRYPTER_VER}-dist.zip
            - echo 'Setter opp og legger inn avhengigheter'
            - cp .env.example .env
            - mv ${SVARINN_EXCEL_LOOKUP_FILE} *.pem example.json storage/
            - composer install --no-dev
            - echo 'Kjører svarinn2pureservice'
            - ./artisan svarinn2pureservice:run

    tool-build-dekrypter:
      - step:
          image: maven:3.8-openjdk-11-slim
          name: Laster ned og bygger ks-dekrypter (som test)
          clone:
            enabled: false
          script:
            - apt-get update &&	apt-get install -y --no-install-recommends git
            - git clone https://github.com/DirektoratetForByggkvalitet/svarut-dekrypter.git
            - cd svarut-dekrypter
            - mvn -e package
          artifacts:
            - "**/target/*.zip"

