

definitions:
  images:
    - image: &dibkphp
        name: dibknoe.azurecr.io/php:latest
        username: $REGISTRY_USERNAME
        password: $REGISTRY_PASSWORD

# Setter maksimum kjøretid for et steg
options:
  max-time: 60

image: *dibkphp

pipelines:
  custom:
    jamf2pureservice:
      - step:
          name: Synkroniser mellom Jamf Pro og Pureservice
          deployment: Production
          script:
            - cp .env.example .env
            - composer install --no-dev
            - ./artisan jamf2pureservice:run
    jamf2ps-test:
      - step:
          name: Synkroniser mellom Jamf Pro og Pureservice
          deployment: Test
          script:
            - cp .env.example .env
            - composer install --no-dev
            - ./artisan jamf2pureservice:run
    svarinn2pureservice:
      - step:
          name: Forbereder kjøring
          image: atlassian/default-image:3
          clone:
            enabled: false
          artifacts:
            - "*.pem"
            - "*.xlsx"
            - "*.json"
          script:
            - echo "Laster ned privatnøkkel til dekryptering fra Key Vault"
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_SP_ID
                AZURE_PASSWORD: $AZURE_SP_SECRET
                AZURE_TENANT_ID: $AZURE_SP_TENANT
                CLI_COMMAND: az keyvault secret download --file privatekey.tmp --name ${AZURE_KV_KEY_NAME} --vault-name ${AZURE_KV_NAME}
            - echo -e "-----BEGIN PRIVATE KEY-----\n$(cat privatekey.tmp)\n-----END PRIVATE KEY-----" > privatekey.pem
            - echo "Laster ned kommunefil fra Azure Blob Storage"
            - pipe: microsoft/azure-cli-run:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_SP_ID
                AZURE_PASSWORD: $AZURE_SP_SECRET
                AZURE_TENANT_ID: $AZURE_SP_TENANT
                CLI_COMMAND: az storage blob download --auth-mode login --file ${BITBUCKET_CLONE_DIR}/${SVARINN_EXCEL_LOOKUP_FILE} --name ${SVARINN_EXCEL_LOOKUP_FILE} --container-name ${STORAGE_CONTAINER} --no-progress --account-name ${STORAGE_ACCOUNT_NAME}

      - step:
          name: Sjekker innkommende forsendelser i Svarinn
          deployment: Production
          script:
            - echo 'Installerer OpenJDK 11 og CMS dekrypter'
            - apk add openjdk11 unzip
            - curl -LO https://github.com/DirektoratetForByggkvalitet/svarut-dekrypter/releases/download/${DEKRYPTER_VER}/dekrypter-${DEKRYPTER_VER}-dist.zip
            - unzip dekrypter-${DEKRYPTER_VER}-dist.zip && rm dekrypter-${DEKRYPTER_VER}-dist.zip
            - echo 'Setter opp og legger inn avhengigheter'
            - cp .env.example .env
            - mv ${SVARINN_EXCEL_LOOKUP_FILE} *.pem storage/
            - echo 'Kjører svarinn2pureservice'
            - composer install --no-dev
            - ./artisan svarinn2pureservice:run

    tool-build-dekrypter:
      - step:
          image: maven:3.8-openjdk-11-slim
          name: Laster ned og bygger ks-dekrypter (som test)
          deployment: Test
          clone:
            enabled: false
          script:
            - apt-get update &&	apt-get install -y --no-install-recommends git
            - git clone https://github.com/DirektoratetForByggkvalitet/svarut-dekrypter.git
            - cd svarut-dekrypter
            - mvn -e package
          artifacts:
            - "**/target/*.zip"

    masseutsendelse:
      - step:
          deployment: Test
          name: Ser etter masseutsendelser i PS og sørger for å sende dem
          script:
            - composer install --no-dev
            - ./artisan utsendelse:run

    splittInnsynskrav:
      - step:
          deployment: Test
          name: Splitter et innsynskrav gitt med SakID
          script:
            - composer install --no-dev
            - ./artisan innsynskrav:splitt ${SakID}


