

definitions:
  images:
    - image: &dibkphp
        name: dibknoe.azurecr.io/php:latest
        username: $REGISTRY_USERNAME
        password: $REGISTRY_PASSWORD

# Setter maksimum kjøretid for et steg
options:
  max-time: 60

image: *dibkphp

pipelines:
  custom:
    jamf2pureservice:
      - step:
          name: Synkroniser mellom Jamf Pro og Pureservice
          deployment: production
          script:
            - composer install --no-dev
            - cp .env.example .env
            - ./artisan jamf2pureservice:sync
    build-dekrypter:
      - step:
          image: maven:latest
          name: Laster ned og bygger build-dekrypter
          clone:
            enabled: false
          script:
            - git clone https://github.com/ks-no/dekrypter.git
            - cd dekrypter
            - mvn package
          artifacts:
            - "**/target/*.zip"

