

definitions:
  images:
    - image: &dibkphp
        name: dibknoe.azurecr.io/php:latest
        username: $REGISTRY_USERNAME
        password: $REGISTRY_PASSWORD

# Setter maksimum kjøretid for et steg
options:
  max-time: 60

image: *dibkphp

pipelines:
  custom:
    jamf2pureservice:
      - step:
          name: Synkroniser mellom Jamf Pro og Pureservice
          deployment: production
          script:
            - composer install --no-dev
            - cp .env.example .env
            - ./artisan jamf2pureservice:sync
    tool-dekrypter:
      - step:
          image: maven:3.8-openjdk-8-slim
          name: Laster ned og bygger ks-dekrypter
          clone:
            enabled: false
          script:
            - apt-get update &&	apt-get install -y --no-install-recommends git
            - git clone https://github.com/DirektoratetForByggkvalitet/svarut-dekrypter.git
            - cd svarut-dekrypter
            - mvn -e package
          artifacts:
            - "**/target/*.zip"
    test-dekrypter:
      - step:
          name: Laster ned svarut-dekrypter
          clone:
            enabled: false
          script:
            - apk add openjdk11
            - apk add curl unzip
            - DVER="1.0"
            - curl -LO https://github.com/DirektoratetForByggkvalitet/svarut-dekrypter/releases/download/${DVER}/dekrypter-${DVER}-dist.zip
            - unzip dekrypter-${DVER}-dist.zip
            - cd dekrypter-${DVER}/
            - java -jar dekrypter-${DVER}.jar
