name: Jamf2Pureservice

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "15 23 * * 0"

jobs:
  jamf2pureservice:

    runs-on: [self-hosted, docker, macOS]
    environment:
      name: jamf2pureservice

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
    - name: Install dependencies
      run: composer install
    - name: Run Jamf2Pureservice
      run: |
        ./artisan migrate:fresh --force
        ./artisan pureservice:sync-jamf
