name: Tester Teams-kobling

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Target environment"
                required: false
                default: "production"

concurrency:
    group: manual-test-workflow
    cancel-in-progress: true

jobs:
    test:
        name: Test run
        runs-on: 
            - self-hosted

        steps:
            - name: Feilmelding til Teams
              # uses: haroldelopez/ms-teams-notification-action@v1.1.0 # https://github.com/marketplace/actions/ms-teams-notification-action
              uses: toko-bifrost/ms-teams-deploy-card@3.1.2
              with:
                webhook-uri: ${{ secrets.TEAMS_DRIFTSMELDINGER_WEBHOOK_URI }}
                github-token: ${{ github.token }}
                timezone: Europe/Oslo
