name: Tester Teams-kobling

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Target environment"
                required: false
                default: "production"

concurrency:
    group: manual-test-workflow
    cancel-in-progress: true

jobs:
    test:
        name: Test run
        runs-on: 
            - self-hosted

        steps:
            - name: Feilmelding til Teams
              uses: carriquiry-g/ms-teams-notification@v2 # https://github.com/marketplace/actions/microsoft-teams-channel-notification
              with:
                github-token: ${{ github.token }} # this will use the runner's token.
                ms-teams-webhook-uri: ${{ secrets.TEAMS_DRIFTSMELDINGER_WEBHOOK_URI }}
                notification-summary: Testmedling
                notification-style: good
                timezone: Europe/Oslo
                verbose-logging: true