name: Testing

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "15 23 * * 0"

jobs:
  test:

    runs-on: [self-hosted, docker, macOS]
    environment:
      name: jamf2pureservice

    steps:
    - uses: actions/checkout@v4
    - name: Setter opp .env
      run: |
        echo "${{ vars.LARAVEL_ENV }}" > .env
        cat <<EOF >> .env
        PURESERVICE_URL=${{ vars.PURESERVICE_URL }}
        PURESERVICE_APIKEY=${{ secrets.PURESERVICE_APIKEY }}
        MAIL_MAILER=${{ vars.MAILER }}
        cat .env
